blog_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
# create an alias for blogs.views since blogs_main has views.py as well
from blogs import views as BlogsView
# Password reset package
from .views import CustomPasswordResetView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('category/', include('blogs.urls')),
    path('blogs/<slug:blog_slug>/', BlogsView.blogs, name='blogs'),
    path('search/', BlogsView.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # Dashboards
    path('dashboard/', include('dashboards.urls')),

    # Password reset - this overrides the default password reset for email.
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:category_id>/', views.posts_by_category, name='posts_by_category')
]

dashboards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # Category CRUD
    path('categories/', views.categories, name='categories'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/edit/<int:pk>/', views.edit_category, name='edit_category'),
    path('categories/delete/<int:pk>/',
         views.delete_category, name='delete_category'),
    # blog posts CRUD
    path('posts/', views.posts, name='posts'),
    path('posts/add/', views.add_post, name='add_post'),
    path('posts/edit/<int:pk>/', views.edit_post, name='edit_post'),
    path('posts/delete/<int:pk>/', views.delete_post, name='delete_post'),
    # users
    path('users/', views.users, name='users'),
    path('users/add/', views.add_user, name='add_user',),
    path('users/edit/<int:pk>/', views.edit_user, name='edit_user'),
    path('users/delete/<int:pk>/', views.delete_user, name='delete_user'),

]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # corrects the default table name from categorys to categories
    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name


# this is needed to create a dropdown field for choices
STATUS_CHOICES = (
    ("Draft", "Draft"),
    ("Published", "Published"),
)


class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    featured_image = models.ImageField(upload_to='uploads/%Y/%m/%d')
    short_description = models.TextField(max_length=500)
    # blog_body = models.TextField(max_length=3000)
    blog_body = RichTextField()
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="Draft")
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/forms.py
from django import forms
from blogs.models import Category, Blog
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# creates the form for adding a new category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'category', 'featured_image',
                  'short_description', 'blog_body', 'status', 'is_featured')

# UserCreationForm is also used in the User Registration: Blog_main\forms.py
# User model is a default or automatic table in Django


class AddUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'is_active',
                  'is_staff', 'is_superuser', 'groups', 'user_permissions')


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        # limits the form into these fields minus the password1  & password2
        fields = ('username', 'email', 'first_name', 'last_name', 'is_active',
                  'is_staff', 'is_superuser', 'groups', 'user_permissions')

dashboards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blogs.models import Category, Blog
from django.contrib.auth.decorators import login_required

from .forms import CategoryForm, BlogPostForm, AddUserForm, EditUserForm
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# adding a decorator as a restriction and forcing the user to go to login page


@login_required(login_url='login')
def dashboard(request):
    # counts all the categories and posts
    category_count = Category.objects.all().count()
    blogs_count = Blog.objects.all().count
    # print(category_count,blogs_count)
    context = {
        'category_count': category_count,
        'blogs_count': blogs_count,
    }

    return render(request, 'dashboard/dashboard.html', context)


# CRUD FUNCTIONS for Category
def categories(request):
    return render(request, 'dashboard/categories.html')


def add_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('categories')
    form = CategoryForm()
    context = {
        'form': form,
    }
    return render(request, 'dashboard/add_category.html', context)


def edit_category(request, pk):
    category = get_object_or_404(Category, pk=pk)

    if request.method == 'POST':
        # get the new value and replace the current instance
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('categories')

    # gets the category record and pass this as instance to the form
    form = CategoryForm(instance=category)
    context = {
        'form': form,
        'category': category,
    }
    return render(request, 'dashboard/edit_category.html', context)


def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect('categories')

# CRUD FUNCTIONS for Posts


def posts(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'dashboard/posts.html', context)


def add_post(request):
    if request.method == 'POST':
        # get the user entry of new values for new post and handles the images or other files
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # temporarily saving the form
            # assigns the logged user as the author
            post.author = request.user
            # saves now the form named as post
            post.save()
            # print('form is valid')
            # gets the title from the form
            title = form.cleaned_data['title']
            # creates an automatic slug based on the title & to make it unique, we append the PK of this post
            # post.id is generated only when we first save the post.
            post.slug = slugify(title)+'-'+str(post.id)  # this-is-a-new-post-1
            # save again to ignore slug duplicates.
            post.save()
            return redirect('posts')
        else:
            print('form is invalid')
            print(form.errors)

    form = BlogPostForm()
    context = {
        'form': form,
    }
    return render(request, 'dashboard/add_post.html', context)


def edit_post(request, pk):
    # gets the database record details and show these on the form
    post = get_object_or_404(Blog, pk=pk)
    if request.method == 'POST':
        # get the form with updated values including the images
        form = BlogPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid:
            post = form.save()  # gets the form instance
            # in case title was changed
            title = form.cleaned_data['title']
            post.slug = slugify(title)+'-'+str(post.id)
            post.save()
            return redirect('posts')
    form = BlogPostForm(instance=post)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'dashboard/edit_post.html', context)


def delete_post(request, pk):
    post = get_object_or_404(Blog, pk=pk)
    post.delete()
    return redirect('posts')


# CRUD FUNCTIONS for Users


def users(request):
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'dashboard/users.html', context)


def add_user(request):
    if request.method == 'POST':
        # get the user entered values via the form
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users')
        else:
            print(form.errors)
    form = AddUserForm()
    context = {
        'form': form,

    }
    return render(request, 'dashboard/add_user.html', context)


def edit_user(request, pk):

    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users')
    # extracts the database record and show these in the form
    form = EditUserForm(instance=user)
    context = {
        'form': form,
    }
    return render(request, 'dashboard/edit_user.html', context)


def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    return redirect('users')

templates/dashboard/add_category.html
{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.blogs.add_category %}
        <h3>Add New Category</h3>
        <form action="{% url 'add_category' %}" method="POST" style="width:500px">
            {% csrf_token %}

            {{ form | crispy}}

            <button type="submit" class="btm btn-warning">Submit</button>
        </form>
        {% else %}
        <p> You don't have permission to add a category.</p>
        {% endif %}
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/add_post.html
{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.blogs.add_blog %}
        <h3>Add New Post</h3>
        <form action="{% url 'add_post' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy}}
            {{ form.media }}

            <button type="submit" class="btm btn-warning">Submit</button>
        </form>
        {% else %}
        <p> You don't have permission to add a post.</p>
        {% endif %}
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/add_user.html
{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.auth.add_user %}
        <h3>Add New User</h3>
        <form action="{% url 'add_user' %}" method="POST">
            {% csrf_token %}

            {{ form | crispy}}

            <button type="submit" class="btm btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You dont have permission to view this page</h5>
        {% endif %}

    </div>
</div>

{% endblock %}

templates/dashboard/categories.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        <h3>All Categories</h3>
        <!-- Adding of category is restricted to manager and editors only -->
        {% if perms.blogs.add_category %}
        <a href="{% url 'add_category' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>

        {% endif %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Category Name</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    {% if perms.blogs.add_category %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                <!-- Call categories from ContextProcessors.py-->
                {% for cat in categories %}
                <tr>
                    <td>{{forloop.counter}}</th>
                        <!-- you can use cat.category_name or simply cat because of the returned string-->
                    <td>{{cat}}</td>
                    <td>{{cat.created_at}}</td>
                    <td>{{cat.updated_at}}</td>
                    <td>
                        {% if perms.blogs.add_category %}
                        <a href="{% url 'edit_category' cat.id %}"><i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                        <a href="{% url 'delete_category' cat.id %}"><i class="fa fa-trash text-danger"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- Load the side bar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        <span>Logged in as <b>{{ user|title }}</b></span>

        <div class="row">
            <!-- auto-width column for categories block-->
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All Categories</div>
                    <!-- Counts the number of posts-->
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{category_count}}</h5>

                    </div>
                </div>

            </div>
            <!-- auto-width column  for posts block-->
            <div class="col">
                <div class="card border-default mb-3">
                    <div class="card-header text-center text-uppercase font-weight-bold">All Posts</div>
                    <!-- Counts the number of posts-->
                    <div class="card-body text-dark">
                        <h5 class="card-title text-center">{{blogs_count}}</h5>

                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
<br>
<br>

{% endblock %}

templates/dashboard/edit_category.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.blogs.change_category %}
        <h3>Edit Category</h3>
        <form action="{% url 'edit_category' category.id %}" method="POST" style="width:500px">
            {% csrf_token %}

            {{ form | crispy}}

            <button type="submit" class="btm btn-warning">Submit</button>
        </form>
        {% else %}
        <p> You don't have permission to edit a category.</p>
        {% endif %}
        <br>
    </div>
</div>
{% endblock %}

templates/dashboard/edit_post.html
{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.blogs.change_blog %}
        <h3>Edit Blog Post</h3>
        <form action="{% url 'edit_post' post.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy}}
            {{ form.media }}

            <button type="submit" class="btm btn-warning">Submit</button>
        </form>
        {% else %}
        <p> You don't have permission to edit a post.</p>
        {% endif %}
        <br>
    </div>
</div>

{% endblock %}

templates/dashboard/edit_user.html
{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.auth.add_user %}
        <h3>Edit User</h3>
        <form action="" method="POST">
            {% csrf_token %}

            {{ form | crispy}}

            <button type="submit" class="btm btn-warning">Submit</button>
        </form>
        <br>
        {% else %}
        <h5>You dont have permission to view this page.</h5>
        {% endif %}

    </div>
</div>

{% endblock %}

templates/dashboard/posts.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        <h3>All Posts</h3>
        <!-- adding of posts are restricted to managers and editors only -->
        {% if perms.blogs.add_blog %}
        <a href="{% url 'add_post' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        {% endif %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Author</th>
                    <th>Status</th>
                    <th>Feautured</th>
                    {% if perms.blogs.add_blog %}
                    <th>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>{{forloop.counter}}</th>
                    <td><a href="{% url 'blogs' post.slug %}">{{post.title}}</a></td>
                    <td>{{post.category}}</td>
                    <td>{{post.author|title}}</td>
                    <td>{{post.status}}</td>
                    <!-- shows centered icons instead for True/False values-->
                    <td align="center">{% if post.is_featured %}<i class="fa fa-check text-success">{% else %}<i
                                class="fa fa-times text-danger"> {%endif%} </td>

                    <td>
                        {% if perms.blogs.add_blog %}
                        <a href="{% url 'edit_post' post.id %}"><i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                        <a href="{% url 'delete_post' post.id %}"><i class="fa fa-trash text-danger"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/dashboard/sidebar.html
<!-- SIDE BAR for Dashboard pages-->
<div class="col-md-3">
    <div class="nav flex-column nav-pills bg-light" aria-orientation="vertical">
        <!-- making the active menu background dynamic-->
        <a href="{% url 'dashboard' %}"
            class="nav-link {%if '/dashboard/' == request.path %} text-white bg-secondary  {% endif %}">Dashboard</a>

        <!-- restricts the User menu option for manager's use only -->
        <!-- Checks if the user has permission to view the user table-->
        {% if perms.auth.view_user %}
        <a href="{% url 'users' %}"
            class="nav-link {%if '/users/' in request.path %} text-white bg-secondary {% endif %}">Users</a>
        {% endif %}

        <!-- if the other menu items are part of the path: main_address/dashboard/categories_OR_Posts_OR_logout-->
        <a href="{% url 'categories' %}"
            class="nav-link {%if '/categories/' in request.path %} text-white bg-secondary {% endif %}">Categories</a>
        <a href="{% url 'posts' %}"
            class="nav-link {%if '/posts/' in request.path %} text-white bg-secondary {% endif %}">Posts</a>
        <a href="{% url 'logout' %}"
            class="nav-link  {%if '/logout/' in request.path %} text-white bg-secondary {% endif %}">Logout</a>
    </div>

</div>

templates/dashboard/users.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <!-- left vertical menu  sidebar-->
    <!-- load the sidebar here-->
    {% include 'dashboard/sidebar.html'%}

    <!-- right  side content -->
    <div class="col-md-9">
        {% if perms.auth.view_user %}
        <h3>All Users</h3>
        <a href="{% url 'add_user' %}" class="btn btn-dark text-light float-right mb-2">Add New</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Staff</th>
                    <th>Superuser</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{forloop.counter}}</th>
                    <td>{{user.first_name}} {{user.last_name}}</td>
                    <td>{{user.username}}</td>
                    <td>{{user.email}}</td>
                    <!-- shows centered icons instead for True/False values-->
                    <td align="center">{% if user.is_active %}<i class="fa fa-check text-success">{% else %}<i
                                class="fa fa-times text-danger"> {%endif%} </td>
                    </td>
                    <td align="center">{% if user.is_staff %}<i class="fa fa-check text-success">{% else %}<i
                                class="fa fa-times text-danger"> {%endif%} </td>
                    <td align="center">{% if user.is_superuser %}<i class="fa fa-check text-success">{% else %}<i
                                class="fa fa-times text-danger"> {%endif%} </td>
                    <td>
                        <a href="{% url 'edit_user' user.id %}"><i class="fa fa-edit text-success"></i></a>
                        &nbsp;
                        <a href="{% url 'delete_user' user.id %}"><i class="fa fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        {% else %}
        <h5>You dont have permission to view this page</h5>
        {% endif %}
    </div>
</div>
{% endblock %}